services:
- type: web
  name: django-photo-album
  env: python
  region: oregon
  plan: starter
  buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
  startCommand: gunicorn photo_album.wsgi:application --bind 0.0.0.0:$PORT
  envVars:
  - key: DJANGO_SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: CLOUDINARY_CLOUD_NAME
    sync: false
  - key: CLOUDINARY_API_KEY
    sync: false
  - key: CLOUDINARY_API_SECRET
    sync: false
  - key: DJANGO_DEBUG
    value: "False"
    sync: true
  - key: DJANGO_ENV
    value: production
    sync: true
  - key: DJANGO_ALLOWED_HOSTS
    value: .onrender.com
    sync: true
  - key: DJANGO_CSRF_TRUSTED_ORIGINS
    sync: false

databases:
- name: django-photo-album-db
  plan: free
  region: oregon
  databaseName: django_photo_album
